baseURL = "https://archiguru.io"
theme = "LoveIt"
title = "ArchiGuru - The sooner you start to code, the longer the program will take"
defaultContentLanguage = "zh-cn"
languageCode = "zh-CN"
languageName = "ç®€ä½“ä¸­æ–‡"
hasCJKLanguage = true
paginate = 25
enableRobotsTXT = true
enableGitInfo = true
enableEmoji = true
ignoreErrors = ["error-remote-getjson", "error-missing-instagram-accesstoken"]
[author]
  name = "ArchiGuru"
  email = "jonny0624@gmail.com"
  link = "https://github.com/archiguru"
[menu]
  [[menu.main]]
    weight = 1
    identifier = "home"
    pre = "ğŸ¡"
    post = " "
    name = " é¦–é¡µ"
    url = "/"
    title = "ArchiGuru - é¦–é¡µ"
  [[menu.main]]
    weight = 2
    identifier = "section"
    pre = "<i class='fas fa-archive fa-fw'></i>"
    post = " "
    name = " æ–‡ç« "
    url = "/posts/"
    title = "ArchiGuru - æ‰€æœ‰æ–‡ç« "
  [[menu.main]]
    weight = 3
    identifier = "categories"
    pre = "<i class='fa-brands fa-perbyte'></i>"
    post = " "
    name = " åˆ†ç±»"
    url = "/categories/"
    title = "ArchiGuru - æ–‡ç« åˆ†ç±»"
  [[menu.main]]
    weight = 4
    identifier = "tags"
    pre = "<i class='fa-brands fa-twitch'></i>"
    post = " "
    name = " æ ‡ç­¾"
    url = "/tags/"
    title = "æ–‡ç« æ ‡ç­¾"
  [[menu.main]]
    weight = 5
    identifier = "bookmark"
    pre = "<i class='fa-brands fa-mizuni'></i>"
    post = " "
    name = " ä¹¦ç­¾"
    url = "/pages/bookmark/"
    title = "ArchiGuru - å¸¸ç”¨ä¹¦ç­¾"
  [[menu.main]]
    weight = 6
    identifier = "about"
    pre = "<i class='fa-regular fa-address-card'></i>"
    post = " "
    name = " å…³äº"
    url = "/about/"
    title = "ArchiGuru - å…³äº|Ablout"
  [[menu.main]]
    weight = 9
    identifier = "more"
    pre = "<i class='fa-brands fa-dailymotion'></i>"
    post = " "
    name = " æ›´å¤š"
    url = "/pages/more/"
    title = "ArchiGuru - æ›´å¤šå†…å®¹"
[params]
  defaultTheme = "dark"
  gitRepo = "https://github.com/archiguru/archiguru"
  fingerprint = "sha256"
  dateFormat = "2006å¹´01æœˆ02æ—¥"
  title = "ArchiGuru"
  description = "ArchiGuru|Jonny.Chang|ä¸ªäººåšå®¢|æ¶æ„å¸ˆ"
  images = ["/logo.svg"]
  [params.header]
    desktopMode = "fixed"
    mobileMode = "auto"
    [params.header.title]
      logo = "/archiguru-logo.png"
      name = "ArchiGuru"
      pre = ""
      post = ""
      typeit = false
  [params.footer]
    enable = true
    custom = ""
    hugo = false
    copyright = true
    author = true
    since = 2014
    icp = "<a href='http://beian.miit.gov.cn/'; target=_blank>æµ™ICPå¤‡18052140å·</a>"
    license= '<a rel="license external nofollow noopener noreffer" href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank">ArchiGuru, Inc.</a>'
  [params.section]
    paginate = 25
    dateFormat = "01æœˆ02æ—¥"
    rss = 9999
  [params.list]
    paginate = 25
    dateFormat = "01æœˆ02æ—¥"
    rss = 9999
  [params.app]
    title = "ArchiGuru"
    noFavicon = false
    svgFavicon = "logo.svg"
    themeColor = "#ffffff"
    iconColor = "#5bbad5"
    tileColor = "#da532c"
  [params.search]
    enable = true
    type = "algolia"
    contentLength = 8000
    placeholder = "æœç´¢æœ¬ç«™"
    maxResultLength = 20
    snippetLength = 72
    highlightTag = "em"
    absoluteURL = false
    [params.search.algolia]
      index = "index.zh-cn"
      appID = "PASDMWALPK"
      searchKey = "b42948e51daaa93df92381c8e2ac0f93"
  [params.home]
    rss = 9999
    [params.home.profile]
      enable = true
      gravatarEmail = ""
      avatarURL = "/images/head_image.png"
      title = "ArchiGuru"
      subtitle = "Although I still love Java, it's not my intention to fall in love with other technology stack, but I can't choose ..."
      typeit = true
      social = true
      disclaimer = "<p>The content published by the <b>ArchiGuru</b> does not guarantee absolute correctness, and the risks associated with using the content of this site have nothing to do with this site. If there is any infringement in this website, please contact the author and delete it.</p>"
    [params.home.posts]
      enable = true
      paginate = 20
  [params.social]
    GitHub = "archiguru"
    Telegram = "archiguru"
    Email = "jonny6015@icloud.com"
    RSS = true
  [params.page]
    hiddenFromHomePage = false
    hiddenFromSearch = false
    twemoji = true
    lightgallery = true
    ruby = true
    fraction = true
    fontawesome = true
    linkToMarkdown = true
    rssFullText = true
    [params.page.toc]
      enable = true
      keepStatic = true
      auto = true
    [params.page.code]
      copy = true
      maxShownLines = 30
    [params.page.math]
      enable = false
    [params.page.mapbox]
      accessToken = "pk.eyJ1IjoiZGlsbG9uenEiLCJhIjoiY2s2czd2M2x3MDA0NjNmcGxmcjVrZmc2cyJ9.aSjv2BNuZUfARvxRYjSVZQ"
      lightStyle = "mapbox://styles/mapbox/light-v10?optimize=true"
      darkStyle = "mapbox://styles/mapbox/dark-v10?optimize=true"
      navigation = true
      geolocate = true
      scale = true
      fullscreen = true
    [params.page.share]
      enable = true
      Twitter = true
      Facebook = true
      Line = true
      Pocket = true
      Flipboard = true
      Weibo = true
    [params.page.comment]
      enable = false
  [params.typeit]
    speed = 200
    cursorSpeed = 500
    cursorChar = "|"
    duration = -1
  [params.seo]
    image = "/images/Apple-Devices-Preview.png"
    thumbnailUrl = "/images/screenshot.png"
  [params.cookieconsent]
    enable = true
    [params.cookieconsent.content]
      message = "æˆ‘ä»¬ä½¿ç”¨ Cookies æ¥ä¸ªæ€§åŒ–å†…å®¹å’Œå¹¿å‘Šï¼Œæä¾›ç¤¾äº¤åª’ä½“åŠŸèƒ½ï¼Œå¹¶åˆ†ææˆ‘ä»¬çš„æµé‡ã€‚æˆ‘ä»¬è¿˜ä¸æˆ‘ä»¬çš„ç¤¾äº¤åª’ä½“ã€å¹¿å‘Šå’Œåˆ†æåˆä½œä¼™ä¼´å…±äº«æœ‰å…³æ‚¨ä½¿ç”¨æˆ‘ä»¬ç½‘ç«™çš„ä¿¡æ¯ã€‚ç‚¹å‡» [åŒæ„] è¡¨ç¤ºæ‚¨æˆæƒæˆ‘ä»¬æŒ‰ç…§æˆ‘ä»¬çš„[Cookieæ”¿ç­–]ä½¿ç”¨æ‰€æœ‰cookieã€‚å¦‚æœæ‚¨ä¸åŒæ„ï¼Œè¯·ç‚¹å‡» [è®¾ç½®] è¿›è¡Œè‡ªå®šä¹‰é€‰æ‹©ã€‚"
      dismiss = ""
      link = ""
  [params.compatibility]
    polyfill = false
    objectFit = false

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    lineNos = true
    lineNumbersInTable = true
    noClasses = false
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.renderer]
      unsafe = true
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 6
[sitemap]
  changefreq = "weekly"
  filename = "sitemap.xml"
  priority = 0.8
[Permalinks]
  posts = ":year/:month/:filename"
[privacy]
  [privacy.twitter]
    enableDNT = true
  [privacy.youtube]
    privacyEnhanced = true

[mediaTypes]
  [mediaTypes."text/plain"]
    suffixes = ["md"]

[outputFormats.MarkDown]
  mediaType = "text/plain"
  isPlainText = true
  isHTML = false
[outputs]
  home = ["HTML", "RSS", "JSON"]
  page = ["HTML", "MarkDown"]
  section = ["HTML", "RSS"]
  taxonomy = ["HTML", "RSS"]
  taxonomyTerm = ["HTML"]
[languages]
  [languages.zh-cn]
    weight = 1
    languageCode = "zh-CN"
    languageName = "ç®€ä½“ä¸­æ–‡"
    hasCJKLanguage = true
    copyright = "æœ¬ä½œå“é‡‡ç”¨çŸ¥è¯†å…±äº«ç½²å-éå•†ä¸šæ€§ 4.0 å›½é™…è®¸å¯ã€‚"
    [languages.zh-cn.menu]
      [[languages.zh-cn.menu.main]]
        weight = 1
        identifier = "home"
        pre = "ğŸ¡"
        post = " "
        name = " é¦–é¡µ"
        url = "/"
        title = "ArchiGuru - é¦–é¡µ"
      [[languages.zh-cn.menu.main]]
        weight = 2
        identifier = "section"
        pre = "<i class='fas fa-archive fa-fw'></i>"
        post = " "
        name = " æ–‡ç« "
        url = "/posts/"
        title = "ArchiGuru - æ‰€æœ‰æ–‡ç« "
      [[languages.zh-cn.menu.main]]
        weight = 3
        identifier = "categories"
        pre = "<i class='fa-brands fa-perbyte'></i>"
        post = " "
        name = " åˆ†ç±»"
        url = "/categories/"
        title = "ArchiGuru - æ–‡ç« åˆ†ç±»"
      [[languages.zh-cn.menu.main]]
        weight = 4
        identifier = "tags"
        pre = "<i class='fa-brands fa-twitch'></i>"
        post = " "
        name = " æ ‡ç­¾"
        url = "/tags/"
        title = "æ–‡ç« æ ‡ç­¾"
      [[languages.zh-cn.menu.main]]
        weight = 5
        identifier = "bookmark"
        pre = "<i class='fa-brands fa-mizuni'></i>"
        post = " "
        name = " ä¹¦ç­¾"
        url = "/pages/bookmark/"
        title = "ArchiGuru - å¸¸ç”¨ä¹¦ç­¾"
      [[languages.zh-cn.menu.main]]
        weight = 6
        identifier = "about"
        pre = "<i class='fa-regular fa-address-card'></i>"
        post = " "
        name = " å…³äº"
        url = "/about/"
        title = "ArchiGuru - å…³äº|Ablout"
      [[languages.zh-cn.menu.main]]
        weight = 9
        identifier = "more"
        pre = "<i class='fa-brands fa-dailymotion'></i>"
        post = " "
        name = " æ›´å¤š"
        url = "/pages/more/"
        title = "ArchiGuru - æ›´å¤šå†…å®¹"

    [languages.zh-cn.params]
      [languages.zh-cn.params.search]
        enable = true
        type = "algolia"
        contentLength = 8000
        placeholder = "æœç´¢æœ¬ç«™"
        maxResultLength = 20
        snippetLength = 72
        highlightTag = "em"
        absoluteURL = false
        [languages.zh-cn.params.search.algolia]
          index = "index.zh-cn"
          appID = "PASDMWALPK"
          searchKey = "b42948e51daaa93df92381c8e2ac0f93"
      [languages.zh-cn.params.home]
        rss = 9999
        [languages.zh-cn.params.home.profile]
          enable = true
          gravatarEmail = ""
          avatarURL = "/images/head_image.png"
          title = "ArchiGuru"
          subtitle = "è™½ç„¶æˆ‘ä¾æ—§çƒ­çˆ± Javaï¼Œçˆ±ä¸Šå…¶ä»–æŠ€æœ¯æ ˆå¹¶ä¸æ˜¯æˆ‘çš„æœ¬æ„ï¼Œä½†æˆ‘æ— æ³•é€‰æ‹© ... "
          typeit = true
          social = true
          disclaimer = "<p>The content published by the <b>ArchiGuru</b> does not guarantee absolute correctness, and the risks associated with using the content of this site have nothing to do with this site. If there is any infringement in this website, please contact the author and delete it.</p>"
      [languages.zh-cn.params.social]
        GitHub = "archiguru"
        Email = "jonny6015@icloud.com"
        RSS = true
  [languages.en]
    weight = 2
    languageCode = "en"
    languageName = "English"
    hasCJKLanguage = false
    copyright = "This work is licensed under a Creative Commons Attribution-NonCommercial 4.0 International License."
    [languages.en.menu]
      [[languages.en.menu.main]]
        weight = 1
        identifier = "home"
        pre = "ğŸ¡"
        post = " "
        name = " Home"
        url = "/"
        title = "ArchiGuru - Home"
      [[languages.en.menu.main]]
        weight = 2
        identifier = "section"
        pre = "<i class='fas fa-archive fa-fw'></i>"
        post = " "
        name = " Articles"
        url = "/posts/"
        title = "ArchiGuru - All Articles"
      [[languages.en.menu.main]]
        weight = 3
        identifier = "categories"
        pre = "<i class='fa-brands fa-perbyte'></i>"
        post = " "
        name = " Categories"
        url = "/categories/"
        title = "ArchiGuru - Categories"
      [[languages.en.menu.main]]
        weight = 4
        identifier = "tags"
        pre = "<i class='fa-brands fa-twitch'></i>"
        post = " "
        name = " Tags"
        url = "/tags/"
        title = "Tags"
      [[languages.en.menu.main]]
        weight = 5
        identifier = "bookmark"
        pre = "<i class='fa-brands fa-mizuni'></i>"
        post = " "
        name = " Bookmarks"
        url = "/pages/bookmark/"
        title = "ArchiGuru - Bookmarks"
      [[languages.en.menu.main]]
        weight = 6
        identifier = "about"
        pre = "<i class='fa-regular fa-address-card'></i>"
        post = " "
        name = " About"
        url = "/about/"
        title = "ArchiGuru - Ablout"
      [[languages.en.menu.main]]
        weight = 9
        identifier = "more"
        pre = "<i class='fa-brands fa-dailymotion'></i>"
        post = " "
        name = " More"
        url = "/pages/more/"
        title = "ArchiGuru - More"
    [languages.en.params]
      [languages.en.params.search]
        enable = true
        type = "algolia"
        contentLength = 8000
        placeholder = "Sesarch"
        maxResultLength = 20
        snippetLength = 72
        highlightTag = "em"
        absoluteURL = false
        [languages.en.params.search.algolia]
          index = "index.en"
          appID = "PASDMWALPK"
          searchKey = "b42948e51daaa93df92381c8e2ac0f93"
      [languages.en.params.home]
        rss = 9999
        [languages.en.params.home.profile]
          enable = true
          gravatarEmail = ""
          avatarURL = "/images/head_image.png"
          title = "ArchiGuru"
          subtitle = "Although I still love Java, it's not my intention to fall in love with other technology stack, but I can't choose ..."
          typeit = true
          social = true
          disclaimer = "<p>The content published by the <b>ArchiGuru</b> does not guarantee absolute correctness, and the risks associated with using the content of this site have nothing to do with this site. If there is any infringement in this website, please contact the author and delete it.</p>"
      [languages.en.params.social]
        GitHub = "archiguru"
        Telegram = "archiguru"
        Email = "jonny6015@icloud.com"
        RSS = true